### ISSUE TITLE
Rename this organization

### ISSUE THREAD

**Issue by alanvardy** [elixirvictoria/communication#1]
I have arbitrarily named this organization elixirvictoria, but it probably won't stay this way! I am hoping for opinions/suggestions/votes about what people would like to see for the name of this group!

Some options that have been suggested by myself or others:

- Elixir Victoria
- Victoria Elixir
- ElixirVic

What else?

**Comment by alanvardy** [comment]
Once the name is determined a domain can be purchased and a Phoenix app created.

**Comment by bmitch** [comment]
At this point I like `Elixir Victoria` but I'm flexible :)

**Comment by SupaMic** [comment]
I'm partial Elixir Victoria for the official organisation name and I think ElixirVic will eventually become its nickname so for I'd say lets go for ElixirVictoria.com keep it clear and easy to work on SEO and maybe one day if we need a shorter domain ElixirVic.dev will probably still be available.

Unless this guy takes it, [who is actually Elixir Vic](https://github.com/vic?language=elixir&tab=stars)

**Comment by alanvardy** [comment]
Yeah.... Elixir Victoria leaves us open to Elixir, and I find that my tongue trips up on Victoria Elixir.

Unless someone swoops in immediately and has a strong opinion otherwise... **pauses for dramatic effect** ... I think Elixir Victoria is a winner.

**Comment by bmitch** [comment]
Awesome!

**Comment by alanvardy** [comment]
I think we are committed! Closing issue.
