### ISSUE TITLE
When should we run the meetup?

### ISSUE THREAD

**Issue by alanvardy** [elixirvictoria/communication#3]
The last time I ran the meetup it was at 1pm on the first Saturday of every month, and that worked fairly well for me. Are there other preferences?

**Comment by bmitch** [comment]
I would prefer after work on a worknight (say around 5 or 6) but if others are avaialble at other times don't let that stop you.

**Comment by alanvardy** [comment]
@SupaMic is graciously providing the location, and it is looking like it will likely be the first Thursday of the month at 6pm.

**Comment by bmitch** [comment]
That would be great!

**Comment by Baradoy** [comment]
I am late to the conversation.
I usually prefer meetups to be at the end of the work day, around 3:30 or so. Although it can conflict with meetings sometimes, I find it can be helpful for people that can count the time as professional development. 
For me personally, Thursdays after 6 will seldom work.

**Comment by bmitch** [comment]
3:30 would also work for me but that's probably the very earliest I could make it.

**Comment by alanvardy** [comment]
I am more flexible on time so any of these options work for me, ping @SupaMic

**Comment by SupaMic** [comment]
I'll have to double check on the availability of the space but probably ok for 3:30pm or 4pm

**Comment by alanvardy** [comment]
Is 3:30pm pretty standard for the end of the workday for tech companies in Victoria? Should we make it 4pm to give people time to grab a sandwich?

I would like to make sure as many people have the opportunity to attend... without being so late that they are forced to skip it!

**Comment by Baradoy** [comment]
I think it is pretty common for the workday to end around 5. I have seen some meetups work by having it take place during the workday and be counted as professional development. When the meetup is after 5, I find people with kids are often excluded. 
Admittedly, there is always going to be some people that are excluded.
Edit:  I don't have that issue myself, but I also like to have the work day mostly contained.

**Comment by alanvardy** [comment]
It is looking like it will be February 6 from 4-6pm, when is the earliest that I can make it official @SupaMic ?

**Comment by SupaMic** [comment]
Due to some miscommunication within my household, I will be unavailable as originally intended on Thursday Feb 6th so we can move it to Wednesday Feb 5th, at the same time 4-6pm.

I hope this is still a good time for everyone.  I will be adding this to the Elixir Victoria website ASAP.

**Comment by alanvardy** [comment]
So this time it will be the first Wednesday, the following times it will be the next Thursday.

**Comment by matthewlehner** [comment]
There's a [developer breakfast meetup](https://www.meetup.com/con-cat) that happens on the first Thursday of every month. 

Would you be open to moving to a different week of the month so that those of use who'd like to attend both can easily do that?

**Comment by alanvardy** [comment]
I’m open to moving it to another day starting March if there is good reason, and having it on the same day as another popular meetup is a good reason. Can everyone weigh in on what days work/don’t work for you?

I’d like this to be the (hopefully) last time we move  the day of the week (we’ve already done it once) as it can be a source of confusion!

So let’s get this right 🙂

**Comment by alanvardy** [comment]
Oh, and @SupaMic is providing the location so he has veto power 🔨

**Comment by matthewlehner** [comment]
I'm not super opinionated about day as much as week (and don't want to make things change if most of the community is happy with the time!).

That said, personally, Wednesdays afternoons don't work (again, no big deal if that's the best day for most folks), and there are two regular events that happen the first week of the month.

So, I'd suggest the second, or third Thursday of the month.

**Comment by SupaMic** [comment]
Thursdays are best for me, 2nd or 3rd on the month will work fine, I just
need to check the availability of the room.

**Comment by alanvardy** [comment]
Alright, 2nd Thursday of the month is now chiselled into stone. Thank you everyone for your input!

**Comment by SupaMic** [comment]
March 12th and April 9th, Community Room is booked
